### ISSUE TITLE
latitude out of range bug

### ISSUE THREAD

**Issue by gnsx** [paulmach/go.geo#72]
`[{"Location":[27.100918,93.691639]},{"Location":[27.10092,93.691639]}]`

The above two points fail to cluster with a panic. I have a couple of more cases where it fails with a similar error. 

I'm no math wiz, so reporting the issue.

```
panic: geo: latitude out of range, given 93.691639

goroutine 1 [running]:
github.com/paulmach/go%2egeo.MercatorScaleFactor(0x40576c43d03968d7, 0xc002415560)
        /home/org/.go/pkg/mod/github.com/paulmach/go.geo@v0.0.0-20180829195134-22b514266d33/projections.go:36 +0x112
github.com/paulmach/go.geo/clustering.geocluster(0xc002460ca0, 0x2, 0x2, 0x4034000000000000, 0xa55ca0, 0xc000000000, 0xc002a89260)
        /home/org/.go/pkg/mod/github.com/paulmach/go.geo@v0.0.0-20180829195134-22b514266d33/clustering/clustering.go:106 +0x106
github.com/paulmach/go.geo/clustering.ClusterGeoPointers(0xc000136e20, 0x2, 0x2, 0x4034000000000000, 0x2, 0x2, 0x0)
        /home/org/.go/pkg/mod/github.com/paulmach/go.geo@v0.0.0-20180829195134-22b514266d33/clustering/clustering.go:75 +0x1ab
clusterhelper.ComputeClusteringData(0xc000546000, 0xbc3, 0xd62, 0xc004251e58, 0x1, 0x1, 0x0, 0xc002415300)
        /home/org/org/go-scripts/correct-data/cluster-helper/cluster-helper.go:43 +0x55d
main.main()
        /home/org/org/go-scripts/correct-data/correct-data.go:105 +0x7f6
exit status 2
```

**Comment by gnsx** [comment]
had lat,lon flipped
